name: karthi_task
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  collection: ^1.15.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  camera: ^0.5.6+3
  path_provider: ^1.4.0
  thumbnails:
    git:
      url: https://github.com/divyanshub024/Flutter_Thumbnails.git
  video_player: ^0.10.2+5
  esys_flutter_share: ^1.0.2
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true




  name: flutter_background_geolocation
  description: The most sophisticated background location tracking & geofencing module with battery-conscious motion-detection intelligence for iOS and Android.
  version: 4.3.0
  homepage: https://github.com/transistorsoft/flutter_background_geolocation

  dependencies:
    flutter:
      sdk: flutter

  flutter:
    plugin:
      platforms:
        android:
          package: com.transistorsoft.flutter.backgroundgeolocation
          pluginClass: FLTBackgroundGeolocationPlugin
        ios:
          pluginClass: FLTBackgroundGeolocationPlugin

  environment:
    sdk: '>=2.12.0 <3.0.0'
    flutter: ">=1.20.0"

